### ISSUE TITLE
Investigate and add Value of Agr Commodities Produced 2016-17 - State and NRMs

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/InvestorMap#239]
ABS publishes the Value of Agr Commodities produced, 2016-17
https://www.abs.gov.au/AUSSTATS/abs@.nsf/DetailsPage/7503.02016-17?OpenDocument

**Comment by reginapramesti** [comment]
![](https://user-images.githubusercontent.com/16102484/55778941-9bd6c680-5ae7-11e9-8cb8-02923da46a13.png)
I could add the data (and it ends up being like the image above) by doing the following:
* Downloaded the .csv file with SA4 regions
* Removed the rows which are not used as part of the data (first four rows, and last 5 rows)
* Renamed the first column to sa4
    * Removed the rows with region codes 0, 1, 2, 3, 4, 5, 6, 7, 8 (essentially I only kept the SA4 region codes). This would depend on which regions we want to use
* Removed the rows with Gross values/Local values of 'np'
* Removed the rows with 'Relative Standard Errors' of '\*\*'. This was because it says that values labelled as '\*\*' is not accurate - not sure if it was necessary to do this

InvestorMap will show a warning message about each region having more than one value (due to there being multiple commodity types for each region). So I also filtered the commodity to just 'Total agriculture' to get the above.

I suppose if we were to add this data as a new layer, the data would have to be formatted in the way I described above?

**Comment by AnaBelgun** [comment]
I think is important to show all types of commodities somehow. 
Maybe an option would be to create separate files (one for each type of region: State, NRMs and SA4) and have the commodities as variables (shown as "displayed variable" in the workbench). One example would be the Tourism data CSVs. The problem here is the number of commodities/variables = 84 which is too big. So to make it work, only select the total for each commodity (not the breakdown; e.g. broadacre crops total, hay total etc.) 

@steve9164 do you have any ideas?

**Comment by AnaBelgun** [comment]
I'm also checking with ABS to see if they have any plans on providing this as an API through http://stat.data.abs.gov.au/

**Comment by AnaBelgun** [comment]
@reginapramesti to confirm with the team (especially @steve9164)  if the app can show nested variables (under "hay" show all as ad drop down list: lucerne, other pasture, cereal etc) and how to deal with showing data for all 3 region types (State, NRMs and SA4). 
Worst case we show one layer per region and only the main commodities totals as variables: broadacre crops, hay, nurseries, cut flowers etc) + the top ones: total agriculture, total crops. 

![image](https://user-images.githubusercontent.com/18452161/56078739-ec735a00-5e2e-11e9-93a4-eaba4a395a33.png)

**Comment by stevage** [comment]
I have taken the approach of two levels of grouping (region type, then first level category), with the lowest level of subcategory as items:

<img width="806" alt="Screenshot 2019-04-15 17 41 50" src="https://user-images.githubusercontent.com/678344/56115053-e05dd880-5fa5-11e9-8cc5-05ac52da2962.png">

<img width="869" alt="Screenshot 2019-04-15 17 40 40" src="https://user-images.githubusercontent.com/678344/56115070-e6ec5000-5fa5-11e9-966c-e7a13a0542d7.png">

It's not perfect though, because some of the subcategories only really make sense as "other" categories, which depend on other intermediate category levels which aren't included:

<img width="281" alt="Screenshot 2019-04-15 17 44 00" src="https://user-images.githubusercontent.com/678344/56115133-0e431d00-5fa6-11e9-8fc1-565183caf2bb.png">

**Comment by stevage** [comment]
So now I'm just wondering how far to polish this. Is this an important dataset? It has some rough edges, but it's pretty functional.

**Comment by stevage** [comment]
@reginapramesti would you mind having a quick look and giving me your comments?

**Comment by reginapramesti** [comment]
It looks good to me, this implementation covers everything that Ana is looking for above. I can see why the "other" layers can be confusing. Could we maybe include the intermediate category levels and use that as a subcategory (eg. Fruit and nuts -> Citrus fruit -> Oranges, as opposed to Fruit and nuts -> Oranges)? 

I'm also getting a message that says 507 is an unknown NRM code for some of them, since it doesn't seem to be in the NRM region mapping JSON file. Other than that everything looks fine. Thanks @stevage!

**Comment by stevage** [comment]
>Could we maybe include the intermediate category levels and use that as a subcategory (eg. Fruit and nuts -> Citrus fruit -> Oranges, as opposed to Fruit and nuts -> Oranges)?

Yeah, it's definitely possible, just adds complexity to the code. Particularly 'cause I want this to not be data dependent (so if ABS adds different subcategories next year it should still work). I might have another poke.

**Comment by reginapramesti** [comment]
I'd probably wait for @AnaBelgun's comment before polishing the code since she would know better regarding how polished the categories should be.

**Comment by stevage** [comment]
Yeah. It's going to be a bit brain-bendy to support arbitrary numbers of intermediate categories.

**Comment by stevage** [comment]
OTOH, https://github.com/TerriaJS/InvestorMap/issues/240 deals with CSVs in exactly the same structure, and there may well be more in the future.

**Comment by stevage** [comment]
![Screenshot 2019-04-18 13 54 11](https://user-images.githubusercontent.com/678344/56335835-7598e100-61e1-11e9-8b00-1cb7164abf46.png)

OK I did it properly.

**Comment by AnaBelgun** [comment]
@stevage @reginapramesti thanks a lot. The fact that subgroups such as Broadacre crops, fruits and nuts are further broken down is great; I don't think we should go a level further down than Mandarins level (which is the 3rd)

**Comment by stevage** [comment]
"Not going further down" means we have to find a way to aggregate them, which is much more complicated. In some cases, there is a "Total". In others there isn't.

**Comment by AnaBelgun** [comment]
Ok @stevage I thought is the other way round; I didn't mean to change anything from what you did; from the screenshot I understood the mandarins level will be included if available

**Comment by stevage** [comment]
Yeah, the way I have done it now is it will turn any level of subcategory into additional levels of grouping within our tree.
